In [187]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [188]:
train = pd.read_csv('/home/harsha/Downloads/titanic_train.csv', sep= ",")

In [190]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [191]:
def add_age(cols):
    Age = cols[0]
    Pclass = cols[1]
    if pd.isnull(Age):
        return int(train[train["Pclass"] == Pclass]["Age"].mean())
    else:
        return Age
train["Age"] = train[["Age","Pclass"]].apply(add_age,axis=1)

In [192]:
train.drop("Cabin",inplace=True,axis=1)

In [193]:
train.dropna(inplace=True)

In [194]:
sex = pd.get_dummies(train["Sex"],drop_first=True)
embarked = pd.get_dummies(train["Embarked"],drop_first=True)
pclass = pd.get_dummies(train["Pclass"],drop_first=True)
train = pd.concat([train,pclass,sex,embarked],axis=1)
train.drop(["PassengerId","Pclass","Name","Sex","Ticket","Embarked"],axis=1,inplace=True)
X_train = train.drop("Survived",axis=1)
X_train = np.array(X_train)
y_train = train.iloc[:, [-1]].values
X_train

array([[22.,  1.,  0., ...,  1.,  0.,  1.],
       [38.,  1.,  0., ...,  0.,  0.,  0.],
       [26.,  0.,  0., ...,  0.,  0.,  1.],
       ...,
       [25.,  1.,  2., ...,  0.,  0.,  1.],
       [26.,  0.,  0., ...,  1.,  0.,  0.],
       [32.,  0.,  0., ...,  1.,  1.,  0.]])

In [195]:
alpha = 10
iters = 1000
theta = np.ones([1,9])

In [196]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [197]:
def compute_cost(X, y, theta):
    m = len(y)
    epsilon = 1e-5
    h = sigmoid(X @ theta)
    cost = (1/m)*(((-y).T @ np.log(h + epsilon))-((1-y).T @ np.log(1-h + epsilon)))
    return cost

In [198]:
def gradient_descent(X, y, theta, alpha, iters):
    m = len(y)
    cost = np.zeros((iters,1))

    for i in range(iters):
        theta = theta - (alpha/m) * (X.T @ (sigmoid(X @ theta) - y)) 
        cost[i] = compute_cost(X, y, theta)

    return (cost, theta)

In [199]:
compute_cost(X_train, y_train, theta.T)
sigmoid(X_train)

array([[1.        , 0.73105858, 0.5       , ..., 0.73105858, 0.5       ,
        0.73105858],
       [1.        , 0.73105858, 0.5       , ..., 0.5       , 0.5       ,
        0.5       ],
       [1.        , 0.5       , 0.5       , ..., 0.5       , 0.5       ,
        0.73105858],
       ...,
       [1.        , 0.73105858, 0.88079708, ..., 0.5       , 0.5       ,
        0.73105858],
       [1.        , 0.5       , 0.5       , ..., 0.73105858, 0.5       ,
        0.5       ],
       [1.        , 0.5       , 0.5       , ..., 0.73105858, 0.73105858,
        0.5       ]])

In [200]:
gradient_descent(X_train, y_train, theta.T, alpha, iters)

/home/harsha/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


(array([[-2.12671836e+03],
        [ 3.17470071e+00],
        [-5.79172366e+02],
        [ 3.17470071e+00],
        [-2.12671836e+03],
        [ 3.17470071e+00],
        [-1.54328428e+01],
        [-2.04997050e+03],
        [ 3.17470071e+00],
        [-3.04704161e+02],
        [-1.94916217e+02],
        [-7.95184367e+02],
        [ 3.17470071e+00],
        [-2.12671836e+03],
        [ 3.17470071e+00],
        [ 3.17470071e+00],
        [-1.50128689e+03],
        [ 3.17470071e+00],
        [-3.04579324e+02],
        [ 3.17470071e+00],
        [-2.12671836e+03],
        [ 3.17470071e+00],
        [-4.46917619e+02],
        [ 3.17470071e+00],
        [-2.12671836e+03],
        [ 3.17470071e+00],
        [-1.95412807e+02],
        [-5.61933613e+02],
        [ 3.17470071e+00],
        [-2.12671836e+03],
        [ 3.17470071e+00],
        [ 3.17470071e+00],
        [-2.07718295e+03],
        [ 3.17470071e+00],
        [-2.26320300e+02],
        [-3.87354675e+02],
        [ 3.17470071e+00],
 

In [201]:
def predict(X, theta):
    return np.floor(sigmoid(X @ theta))
c = predict(X_train, theta.T)

In [202]:
def accuracy(c, y):
    diff = c - y
    return 1.0 - (float(np.count_nonzero(diff == 1))/len(diff))
accuracy(c , y_train)

0.8211473565804275

In [203]:
test = pd.read_csv('/home/harsha/Downloads/titanic_test.csv', sep =',', error_bad_lines=False)
def add_age(cols):
    Age = cols[0]
    if pd.isnull(Age):
        return int(test[:]["Age"].mean())
    else:
        return Age
test["Age"] = test[["Age"]].apply(add_age,axis=1)
test.drop("Cabin",inplace=True,axis=1)
test.dropna(inplace=True)
sex = pd.get_dummies(test["Sex"],drop_first=True)
embarked = pd.get_dummies(test["Embarked"],drop_first=True)
pclass = pd.get_dummies(test["Pclass"],drop_first=True)
test = pd.concat([test,pclass,sex,embarked],axis=1)
test.drop(["PassengerId","Pclass","Name","Sex","Ticket","Embarked"],axis=1,inplace=True)
X_test = np.array(test)
ones = np.ones([X_test.shape[0], 1]) 
X_test

b'Skipping line 419: expected 11 fields, saw 21\n'


array([[34.5,  0. ,  0. , ...,  1. ,  1. ,  0. ],
       [47. ,  1. ,  0. , ...,  0. ,  0. ,  1. ],
       [62. ,  0. ,  0. , ...,  1. ,  1. ,  0. ],
       ...,
       [38.5,  0. ,  0. , ...,  1. ,  0. ,  1. ],
       [30. ,  0. ,  0. , ...,  1. ,  0. ,  1. ],
       [30. ,  1. ,  1. , ...,  1. ,  0. ,  0. ]])

In [204]:
predict_test = predict(X_test , theta.T)
predict_test

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],